export const CAPITALS_LIST = [
  'Kabul',
  'Tirana',
  'Algiers',
  'Andorra la Vella',
  'Luanda',
  'Saint John’s',
  'Buenos Aires',
  'Yerevan',
  'Canberra',
  'Vienna',
  'Baku',
  'Nassau',
  'Manama',
  'Dhaka',
  'Bridgetown',
  'Minsk',
  'Brussels',
  'Belmopan',
  'Porto-Novo',
  'Thimphu',
  'La Paz',
  'Sucre',
  'Sarajevo',
  'Gaborone',
  'Brasília',
  'Bandar Seri Begawan',
  'Sofia',
  'Ouagadougou',
  'Gitega',
  'Praia',
  'Phnom Penh',
  'Yaoundé',
  'Ottawa',
  'Bangui',
  'N’Djamena',
  'Santiago',
  'Beijing',
  'Bogotá',
  'Moroni',
  'Kinshasa',
  'Brazzaville',
  'San José',
  'Zagreb',
  'Havana',
  'Nicosia',
  'Prague',
  'Copenhagen',
  'Djibouti',
  'Roseau',
  'Santo Domingo',
  'Quito',
  'Cairo',
  'San Salvador',
  'Malabo',
  'Asmara',
  'Tallinn',
  'Mbabane',
  'Lobamba',
  'Addis Ababa',
  'Suva',
  'Helsinki',
  'Paris',
  'Libreville',
  'Banjul',
  'Tbilisi',
  'Berlin',
  'Accra',
  'Athens',
  'Saint George’s',
  'Guatemala City',
  'Conakry',
  'Bissau',
  'Georgetown',
  'Port-au-Prince',
  'Tegucigalpa',
  'Budapest',
  'Reykjavik',
  'New Delhi',
  'Jakarta',
  'Tehran',
  'Baghdad',
  'Dublin',
  'Rome',
  'Kingston',
  'Tokyo',
  'Amman',
  'Nur-Sultan',
  'Nairobi',
  'Tarawa',
  'Pristina',
  'Kuwait City',
  'Bishkek',
  'Vientiane',
  'Riga',
  'Beirut',
  'Maseru',
  'Monrovia',
  'Tripoli',
  'Vaduz',
  'Vilnius',
  'Luxembourg',
  'Antananarivo',
  'Lilongwe',
  'Kuala Lumpur',
  'Malé',
  'Bamako',
  'Valletta',
  'Majuro',
  'Nouakchott',
  'Port Louis',
  'Mexico City',
  'Palikir',
  'Chisinau',
  'Monaco',
  'Ulaanbaatar',
  'Podgorica',
  'Rabat',
  'Maputo',
  'Naypyidaw',
  'Windhoek',
  'Yaren',
  'Kathmandu',
  'Amsterdam',
  'Wellington',
  'Managua',
  'Niamey',
  'Abuja',
  'Pyongyang',
  'Oslo',
  'Muscat',
  'Islamabad',
  'Ngerulmud',
  'Jerusalem',
  'Panama City',
  'Port Moresby',
  'Asunción',
  'Lima',
  'Manila',
  'Warsaw',
  'Lisbon',
  'Doha',
  'Bucharest',
  'Moscow',
  'Kigali',
  'Basseterre',
  'Castries',
  'Kingstown',
  'Apia',
  'San Marino',
  'São Tomé',
  'Riyadh',
  'Dakar',
  'Belgrade',
  'Victoria',
  'Freetown',
  'Singapore',
  'Bratislava',
  'Ljubljana',
  'Honiara',
  'Mogadishu',
  'Pretoria',
  'Bloemfontein',
  'Cape Town',
  'Seoul',
  'Juba',
  'Madrid',
  'Colombo',
  'Khartoum',
  'Paramaribo',
  'Stockholm',
  'Bern',
  'Damascus',
  'Taipei',
  'Dushanbe',
  'Dodoma',
  'Bangkok',
  'Lomé',
  'Nukuʻalofa',
  'Port of Spain',
  'Tunis',
  'Ankara',
  'Ashgabat',
  'Funafuti',
  'Kampala',
  'Kyiv',
  'Abu Dhabi',
  'London',
  'Washington',
  'Montevideo',
  'Tashkent',
  'Port Vila',
  'Vatican City',
  'Caracas',
  'Hanoi',
  'Sana’a',
  'Lusaka',
  'Harare',
] as const

export const PERIOD_OPTIONS = [6, 12, 24, 72, 168] as const

type Capital = (typeof CAPITALS_LIST)[number]

export const CAPITALS = CAPITALS_LIST.reduce<Record<Capital, string>>(
  (acc, item) => {
    return { ...acc, [item]: item }
  },
  {} as Record<Capital, string>
)
