name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run full test suite
        run: |
          npm run lint
          npx tsc --noEmit
          npm run format:check
          npm run build

      - name: Check bundle size
        run: |
          npm run build
          du -sh dist/

